### ISSUE TITLE
感觉可以做优化的地方

### ISSUE THREAD

**Issue by blankleee** [yilingyi/k8s-java-thread-dumper#1]
目前这个方案对应用容器环境有一定需求。1.要能出公网；2.需要有curl命令。但是现在基本上都用最小镜像的原则去构建应用容器。
感觉可以优化的地方是：
把arthas的包放在容器里，直接通过推送的方法把包推到目标容器，再执行脚本，这样对应用容器的环境需求可以降低。

**Comment by yilingyi** [comment]
谢谢你的宝贵建议，这个可以有！

**Comment by yilingyi** [comment]
该项目的2.1.0版本已支持arthas远程拷贝，满足极简容器环境运行，另增加了prometheus告警回调
