### ISSUE TITLE
感觉可以优化的地方

### ISSUE THREAD

**Issue by xudingjun3131** [yilingyi/k8s-java-thread-dumper#2]
现在是强依赖grafana。
有一些告警是依赖alertmanager或者prometheus的。
这些采集数据之后可以单独出来决定。
又或者提供一个url去触发dump操作。相信更多人应该需要的是threaddump数据。

**Comment by liucx1201** [comment]
是的

**Comment by yilingyi** [comment]
谢谢，正在考虑prometheus alertmanager去做触发。

**Comment by yilingyi** [comment]
该项目的2.1.0版本已支持prometheus告警回调
